### ISSUE TITLE
Excluding URIs From CSRF Protection

### ISSUE THREAD

**Issue by u01jmg3** [laravel/passport#212]
- I hope this is an appropriate question - I was wondering if there was a method of excluding CSRF protection in Laravel Passport similar to what you can do in the framework?
  - https://laravel.com/docs/5.3/csrf#csrf-excluding-uris
- Premise of the question relates to having an internal API I consume in my application. I would like to be able to view (`GET`) API routes out with the application during development without being pushed to login (even though I already am).
  - Being able to disable CSRF protection on API routes would permit this.
  - I believe in the framework CSRF protection is excluded if the request is a reading request (HEAD, GET, OPTIONS).

**Comment by Modelizer** [comment]
We don't have CSRF protection on Passport routes.

Are you not using `php artisan route:list` command to view routes?

**Comment by u01jmg3** [comment]
> We don't have CSRF protection on Passport routes.

https://github.com/laravel/passport/blob/1.0/src/Guards/TokenGuard.php#L201

> Are you not using php artisan route:list command to view routes?

I'm referring to viewing the JSON output by visiting an API route directly in my browser. I can't do this as the `X-CSRF-TOKEN` header is missing. If I was able to disable this on GET or API routes it would be okay.

**Comment by Modelizer** [comment]
My point is CSRF is handled by middleware we are not binding inside routes.

https://github.com/laravel/passport/blob/1.0/src/RouteRegistrar.php#L48 Here we reference `auth` as a middleware which binds Laravel CSRF validation with Passport.

My suggestion would be you can copy all routes from `RouteRegistrar` and put it in your own routes this way you can exclude CSRF validation by creating and mapping a new middleware.

Regarding route listing, I think there are some packages which do this job... 🤔  Not sure you can google it out.

**Comment by u01jmg3** [comment]
> My point is CSRF is handled by middleware we are not binding inside routes.

Thanks for your help

> My suggestion would be you can copy all routes from RouteRegistrar and put it in your own routes this way you can exclude CSRF validation by creating and mapping a new middleware.

Any chance you can provide an example?

---

Any reason putting an exception in [here](https://github.com/laravel/laravel/blob/master/app/Http/Middleware/VerifyCsrfToken.php#L14) doesn't work if Passport uses `auth`?

**Comment by Modelizer** [comment]
That would be the shortest way to do. But I'm getting confuse now? you want to control Passport routes. right?

As far as I understand Passport is tightly coupled by Laravel. So if you want to exclude some CSRF routes you can go with https://laravel.com/docs/5.3/csrf#csrf-excluding-uris This will act as a centralize solution regardless of Passport or some other package. (A more recommend way)

**Comment by u01jmg3** [comment]
> You want to control Passport routes. right?

I want to disable CSRF protection on Passport routes, yes. This way I can access API routes without being redirected to login even though I already am logged in. This is happening because I am missing the `X-CSRF-TOKEN` header as I am making a standard `GET` request.

> As far as I understand Passport is tightly coupled with Laravel. So if you want to exclude some CSRF routes you can go with https://laravel.com/docs/5.3/csrf#csrf-excluding-uris This will act as a centralize solution regardless of Passport or some other package. (A more recommend way)

I have already tried this but as above I am redirected to login (even though I already am logged in). Can you explain why this might be happening and what I can do to exclude CSRF protection in Passport?

**Comment by Modelizer** [comment]
It seems your problem is not related to CSRF.

Have you handle exception from [Handler](https://github.com/laravel/laravel/blob/master/app/Exceptions/Handler.php#L47) ? It might be possible that if any exception is thrown then you are redirecting it to some other page?

Or else you need to give us step to reproduce this issue. Or you can setup passport and run it on fresh Laravel instance and try to co-relate it with your existing instance.

**Comment by mleczek** [comment]
@u01jmg3 The [csrf validation middleware](https://github.com/laravel/framework/blob/d03eddbdf0b77fc03b3f185d3171095a72018fd7/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php#L108) and [csrf passport validation](https://github.com/laravel/passport/blob/1.0/src/Guards/TokenGuard.php#L201) aren't the same. The second one can be a bit confused, because passport use csrf token to give use an easy way to integrate Single Page Applications that comes with your application - **this is oauth auth token as well as csrf validation token**.

The problem is that (I also spent some time to realize this - it isn't intuitive) the passport support only one way of 3 available in traditional csrf validation (CSRF header, XSRF header and _token isn't supported). I made a pull request (#183) to fix it, but was rejected. If it will pass then you could access your api routes directly in browser using https://your-domain?_token=here-your-token.

If it is only for dev purposes then you can modify your copy of passport in vendor directory to [support the _token input](https://github.com/laravel/passport/pull/183/commits/522c326c5067bb708441769b9479403a4ad2c0c3).

**Comment by u01jmg3** [comment]
@mleczek - thank you for picking up on my issue and giving some more insight.

These are my findings regarding working with API routes in `api.php`:

- I originally began by using API tokens / `auth:api` that comes with Laravel but quickly found that this is stateless so any valid API token can be used rather than the token related to the logged in user. This is not ideal.

- I then changed to use Laravel Passport. This worked well until I found I could not access any of my API routes directly in a browser without being forced to login (even though I already was). This is because I am not providing the required `X-CSRF-TOKEN` header and there is no way in Passport of excluding CSRF protection from API routes. I therefore think Passport is geared more towards SPA and does not quite have the flexibility I need.

- Finally I switched to using Laravel's standard `auth` implementation and amended the `api` middleware group to have state, the same way `web` does.
  - This means when I am logged in as a user, I must provide the credentials for that user (via a cookie) when directly accessing one of my API routes. (My API routes are defined with the `auth` route middleware.) As soon as I log out I can no longer access these API routes until I log in again.
  - Standard `auth` has the added benefit that CSRF protection is excluded if the request is a reading request (GET, HEAD, OPTIONS).
  
Due to the fact that PR #183 was rejected, I don't think anything more can be done.

**Comment by Modelizer** [comment]
> Finally I switched to using Laravel's standard auth implementation and amended the api middleware group to have state, the same way web does.

That's what I pointed here In my first comment :)
> My suggestion would be you can copy all routes from RouteRegistrar and put it in your own routes this way you can exclude CSRF validation by creating and mapping a new middleware.

Finally, good to know your problem is solved! Regarding SPA I'm working on projects [Lumenite](https://github.com/Qafeen/Lumenite) and [Laravue](https://github.com/Qafeen/Laravue) to solve decouple SPA issue with Laravel or Lumen. Although most of the work is still in progress.

**Comment by u01jmg3** [comment]
> That's what I pointed here in my first comment :)

For me, I didn't find what you said to be very clear. That's why I asked: _Any chance you can provide an example?_ No example was provided.

> Finally, good to know your problem is solved!

My problem isn't really solved. I am not able to use Passport as I wanted to and a PR that was submitted to make things more flexible was rejected so instead I have deferred back to the standard `auth` implementation.

> Regarding SPA...

My point was because my application is not a SPA, Passport isn't flexible enough for me to use.
